enum Direction {
    /**
     * Corresponding UP, LEFT, UPPER_LEFT_DIAGONAL, and UPPER_RIGHT_DIAGONAL, LOWER_LEFT_DIAGONAL, LOWER_RIGHT_DIAGONAL directions.
     */
    UP,
    DOWN,
    LEFT,
    RIGHT,
    UPPER_LEFT_DIAGONAL,
    UPPER_RIGHT_DIAGONAL,
    LOWER_LEFT_DIAGONAL,
    LOWER_RIGHT_DIAGONAL
}